// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Palantir.Infrastructure.Data;

#nullable disable

namespace Palantir.Infrastructure.Migrations
{
    [DbContext(typeof(PalantirDbContext))]
    [Migration("20260620125913_AddWarSideColor")]
    partial class AddWarSideColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Palantir.Domain.Models.Army", b =>
                {
                    b.Property<int>("army_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("army_id"));

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<string>("name_arm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("summary")
                        .HasColumnType("text");

                    b.Property<string>("type_arm")
                        .HasColumnType("text");

                    b.Property<int>("war_side_id")
                        .HasColumnType("integer");

                    b.HasKey("army_id")
                        .HasName("armies_pkey");

                    b.HasIndex(new[] { "war_side_id" }, "idx_armies_war_side_id");

                    b.ToTable("armies");
                });

            modelBuilder.Entity("Palantir.Domain.Models.ArmyPosition", b =>
                {
                    b.Property<int>("army_position_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("army_position_id"));

                    b.Property<int>("army_id")
                        .HasColumnType("integer");

                    b.Property<Point>("coordinate")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<DateOnly>("date_position")
                        .HasColumnType("date");

                    b.Property<string>("note")
                        .HasColumnType("text");

                    b.HasKey("army_position_id")
                        .HasName("army_positions_pkey");

                    b.HasIndex(new[] { "army_id", "date_position" }, "army_positions_army_id_date_position_key")
                        .IsUnique();

                    b.HasIndex(new[] { "date_position" }, "idx_army_positions_date");

                    b.HasIndex(new[] { "coordinate" }, "idx_army_positions_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "coordinate" }, "idx_army_positions_geom"), "gist");

                    b.ToTable("army_positions");
                });

            modelBuilder.Entity("Palantir.Domain.Models.ControlZone", b =>
                {
                    b.Property<int>("control_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("control_id"));

                    b.Property<DateOnly>("date_control")
                        .HasColumnType("date");

                    b.Property<MultiPolygon>("geom")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)");

                    b.Property<string>("precision_control")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("war_id")
                        .HasColumnType("integer");

                    b.Property<int>("war_side_id")
                        .HasColumnType("integer");

                    b.HasKey("control_id")
                        .HasName("control_zones_pkey");

                    b.HasIndex("war_side_id");

                    b.HasIndex(new[] { "geom" }, "idx_control_zones_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "geom" }, "idx_control_zones_geom"), "gist");

                    b.HasIndex(new[] { "war_id", "date_control" }, "idx_control_zones_war_date");

                    b.ToTable("control_zones");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Event", b =>
                {
                    b.Property<int>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("event_id"));

                    b.Property<Point>("coordinate")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<DateOnly>("date_ev")
                        .HasColumnType("date");

                    b.Property<int?>("operation_id")
                        .HasColumnType("integer");

                    b.Property<string>("text_ev")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type_ev")
                        .HasColumnType("text");

                    b.Property<int>("war_id")
                        .HasColumnType("integer");

                    b.Property<int?>("war_side_id")
                        .HasColumnType("integer");

                    b.HasKey("event_id")
                        .HasName("events_pkey");

                    b.HasIndex("operation_id");

                    b.HasIndex("war_side_id");

                    b.HasIndex(new[] { "coordinate" }, "idx_events_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "coordinate" }, "idx_events_geom"), "gist");

                    b.HasIndex(new[] { "war_id", "date_ev" }, "idx_events_war_date");

                    b.ToTable("events");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Operation", b =>
                {
                    b.Property<int>("operation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("operation_id"));

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("summary")
                        .HasColumnType("text");

                    b.Property<int>("theater_id")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("operation_id")
                        .HasName("operations_pkey");

                    b.HasIndex(new[] { "theater_id" }, "idx_operations_theater_id");

                    b.ToTable("operations");
                });

            modelBuilder.Entity("Palantir.Domain.Models.OperationSide", b =>
                {
                    b.Property<int>("operation_id")
                        .HasColumnType("integer");

                    b.Property<int>("war_side_id")
                        .HasColumnType("integer");

                    b.Property<string>("note")
                        .HasColumnType("text");

                    b.Property<string>("role_side")
                        .HasColumnType("text");

                    b.HasKey("operation_id", "war_side_id")
                        .HasName("operation_sides_pkey");

                    b.HasIndex(new[] { "war_side_id" }, "idx_operation_sides_war_side_id");

                    b.ToTable("operation_sides");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Side", b =>
                {
                    b.Property<int>("side_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("side_id"));

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("side_id")
                        .HasName("sides_pkey");

                    b.ToTable("sides");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Theater", b =>
                {
                    b.Property<int>("theater_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("theater_id"));

                    b.Property<string>("summary")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("war_id")
                        .HasColumnType("integer");

                    b.HasKey("theater_id")
                        .HasName("theaters_pkey");

                    b.HasIndex(new[] { "war_id" }, "idx_theaters_war_id");

                    b.ToTable("theaters");
                });

            modelBuilder.Entity("Palantir.Domain.Models.War", b =>
                {
                    b.Property<int>("war_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("war_id"));

                    b.Property<DateOnly?>("end_date")
                        .HasColumnType("date");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.Property<string>("summary")
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("war_id")
                        .HasName("wars_pkey");

                    b.ToTable("wars");
                });

            modelBuilder.Entity("Palantir.Domain.Models.WarSide", b =>
                {
                    b.Property<int>("war_side_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("war_side_id"));

                    b.Property<string>("color_hex")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("joined_date")
                        .HasColumnType("date");

                    b.Property<string>("note")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("out_date")
                        .HasColumnType("date");

                    b.Property<int>("side_id")
                        .HasColumnType("integer");

                    b.Property<int>("war_id")
                        .HasColumnType("integer");

                    b.HasKey("war_side_id")
                        .HasName("war_sides_pkey");

                    b.HasIndex(new[] { "side_id" }, "idx_war_sides_side_id");

                    b.HasIndex(new[] { "war_id" }, "idx_war_sides_war_id");

                    b.HasIndex(new[] { "war_id", "side_id" }, "war_sides_war_id_side_id_key")
                        .IsUnique();

                    b.ToTable("war_sides");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Army", b =>
                {
                    b.HasOne("Palantir.Domain.Models.WarSide", "war_side")
                        .WithMany("armies")
                        .HasForeignKey("war_side_id")
                        .IsRequired()
                        .HasConstraintName("armies_war_side_id_fkey");

                    b.Navigation("war_side");
                });

            modelBuilder.Entity("Palantir.Domain.Models.ArmyPosition", b =>
                {
                    b.HasOne("Palantir.Domain.Models.Army", "army")
                        .WithMany("army_positions")
                        .HasForeignKey("army_id")
                        .IsRequired()
                        .HasConstraintName("army_positions_army_id_fkey");

                    b.Navigation("army");
                });

            modelBuilder.Entity("Palantir.Domain.Models.ControlZone", b =>
                {
                    b.HasOne("Palantir.Domain.Models.War", "war")
                        .WithMany("control_zones")
                        .HasForeignKey("war_id")
                        .IsRequired()
                        .HasConstraintName("control_zones_war_id_fkey");

                    b.HasOne("Palantir.Domain.Models.WarSide", "war_side")
                        .WithMany("control_zones")
                        .HasForeignKey("war_side_id")
                        .IsRequired()
                        .HasConstraintName("control_zones_war_side_id_fkey");

                    b.Navigation("war");

                    b.Navigation("war_side");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Event", b =>
                {
                    b.HasOne("Palantir.Domain.Models.Operation", "operation")
                        .WithMany("events")
                        .HasForeignKey("operation_id")
                        .HasConstraintName("events_operation_id_fkey");

                    b.HasOne("Palantir.Domain.Models.War", "war")
                        .WithMany("events")
                        .HasForeignKey("war_id")
                        .IsRequired()
                        .HasConstraintName("events_war_id_fkey");

                    b.HasOne("Palantir.Domain.Models.WarSide", "war_side")
                        .WithMany("events")
                        .HasForeignKey("war_side_id")
                        .HasConstraintName("events_war_side_id_fkey");

                    b.Navigation("operation");

                    b.Navigation("war");

                    b.Navigation("war_side");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Operation", b =>
                {
                    b.HasOne("Palantir.Domain.Models.Theater", "theater")
                        .WithMany("operations")
                        .HasForeignKey("theater_id")
                        .IsRequired()
                        .HasConstraintName("operations_theater_id_fkey");

                    b.Navigation("theater");
                });

            modelBuilder.Entity("Palantir.Domain.Models.OperationSide", b =>
                {
                    b.HasOne("Palantir.Domain.Models.Operation", "operation")
                        .WithMany("operation_sides")
                        .HasForeignKey("operation_id")
                        .IsRequired()
                        .HasConstraintName("operation_sides_operation_id_fkey");

                    b.HasOne("Palantir.Domain.Models.WarSide", "war_side")
                        .WithMany("operation_sides")
                        .HasForeignKey("war_side_id")
                        .IsRequired()
                        .HasConstraintName("operation_sides_war_side_id_fkey");

                    b.Navigation("operation");

                    b.Navigation("war_side");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Theater", b =>
                {
                    b.HasOne("Palantir.Domain.Models.War", "war")
                        .WithMany("theaters")
                        .HasForeignKey("war_id")
                        .IsRequired()
                        .HasConstraintName("theaters_war_id_fkey");

                    b.Navigation("war");
                });

            modelBuilder.Entity("Palantir.Domain.Models.WarSide", b =>
                {
                    b.HasOne("Palantir.Domain.Models.Side", "side")
                        .WithMany("war_sides")
                        .HasForeignKey("side_id")
                        .IsRequired()
                        .HasConstraintName("war_sides_side_id_fkey");

                    b.HasOne("Palantir.Domain.Models.War", "war")
                        .WithMany("war_sides")
                        .HasForeignKey("war_id")
                        .IsRequired()
                        .HasConstraintName("war_sides_war_id_fkey");

                    b.Navigation("side");

                    b.Navigation("war");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Army", b =>
                {
                    b.Navigation("army_positions");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Operation", b =>
                {
                    b.Navigation("events");

                    b.Navigation("operation_sides");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Side", b =>
                {
                    b.Navigation("war_sides");
                });

            modelBuilder.Entity("Palantir.Domain.Models.Theater", b =>
                {
                    b.Navigation("operations");
                });

            modelBuilder.Entity("Palantir.Domain.Models.War", b =>
                {
                    b.Navigation("control_zones");

                    b.Navigation("events");

                    b.Navigation("theaters");

                    b.Navigation("war_sides");
                });

            modelBuilder.Entity("Palantir.Domain.Models.WarSide", b =>
                {
                    b.Navigation("armies");

                    b.Navigation("control_zones");

                    b.Navigation("events");

                    b.Navigation("operation_sides");
                });
#pragma warning restore 612, 618
        }
    }
}
